//! Buffa-generated owned + view types for serf wire messages.
//!
//! The types in this module are generated at build time from
//! `proto/serf/v1/messages.proto` via `buffa-build` + `buffa-codegen`.
//! Do not edit this file; edit the `.proto` schema instead.
//!
//! # Generated types
//!
//! - [`serf::v1::UserEventMessage`] — user-generated event broadcast
//!
//! All `bytes` fields use [`bytes::Bytes`] (configured via
//! `buffa_build::Config::use_bytes_type()`).

#![allow(missing_docs)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/serf_wire_generated.rs"));

#[cfg(test)]
mod tests;
